In [1]:
import pandas as pd

weather = pd.read_csv('./assets/input/weather.csv')

train = pd.read_csv('./assets/input/train.csv')

train['Date'] = pd.to_datetime(train['Date'])

weather['Date'] = pd.to_datetime(weather['Date'])

In [2]:
print(weather.shape)
print(train.shape)

(2944, 22)
(10506, 12)

In [3]:
weather_station1 = weather.drop_duplicates('Date')

weather['Station_2'] = pd.get_dummies(weather['Station'], drop_first= True)


df = train.merge(weather_station1, how = 'inner', on = 'Date', copy = False)

In [4]:
df.columns

Index(['Date', 'Address', 'Species', 'Block', 'Street', 'Trap',
       'AddressNumberAndStreet', 'Latitude', 'Longitude', 'AddressAccuracy',
       'NumMosquitos', 'WnvPresent', 'Station', 'Tmax', 'Tmin', 'Tavg',
       'Depart', 'DewPoint', 'WetBulb', 'Heat', 'Cool', 'Sunrise', 'Sunset',
       'CodeSum', 'Depth', 'Water1', 'SnowFall', 'PrecipTotal', 'StnPressure',
       'SeaLevel', 'ResultSpeed', 'ResultDir', 'AvgSpeed'],
      dtype='object')

In [5]:
df

,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy,...,CodeSum,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed
0,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
1,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
2,2007-05-29,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
3,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
4,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
5,2007-05-29,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX RESTUANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
6,2007-05-29,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX RESTUANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
7,2007-05-29,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX PIPIENS/RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
8,2007-05-29,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
9,2007-05-29,"1100 West Chicago Avenue, Chicago, IL 60642, USA",CULEX RESTUANS,11,W CHICAGO,T049,"1100 W CHICAGO, Chicago, IL",41.896282,-87.655232,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
10,2007-05-29,"2100 North Stave Street, Chicago, IL 60647, USA",CULEX PIPIENS/RESTUANS,21,N STAVE ST,T050,"2100 N STAVE ST, Chicago, IL",41.919343,-87.694259,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
11,2007-05-29,"2200 North Cannon Drive, Chicago, IL 60614, USA",CULEX PIPIENS/RESTUANS,22,N CANNON DR,T054,"2200 N CANNON DR, Chicago, IL",41.921965,-87.632085,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
12,2007-05-29,"2200 North Cannon Drive, Chicago, IL 60614, USA",CULEX RESTUANS,22,N CANNON DR,T054,"2200 N CANNON DR, Chicago, IL",41.921965,-87.632085,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
13,2007-05-29,"2200 West 113th Street, Chicago, IL 60643, USA",CULEX PIPIENS/RESTUANS,22,W 113TH ST,T086,"2200 W 113TH ST, Chicago, IL",41.688324,-87.676709,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
14,2007-05-29,"2200 West 113th Street, Chicago, IL 60643, USA",CULEX RESTUANS,22,W 113TH ST,T086,"2200 W 113TH ST, Chicago, IL",41.688324,-87.676709,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
15,2007-05-29,"1100 South Peoria Street, Chicago, IL 60608, USA",CULEX RESTUANS,11,S PEORIA ST,T091,"1100 S PEORIA ST, Chicago, IL",41.862292,-87.648860,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
16,2007-05-29,"1700 West 95th Street, Chicago, IL 60643, USA",CULEX RESTUANS,17,W 95TH ST,T094,"1700 W 95TH ST, Chicago, IL",41.720848,-87.666014,9,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
17,2007-05-29,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX RESTUANS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
18,2007-05-29,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX PIPIENS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
19,2007-05-29,"North Streeter Drive, Chicago, IL 60611, USA",CULEX PIPIENS/RESTUANS,53,N STREETER DR,T129,"5300 N STREETER DR, Chicago, IL",41.891126,-87.611560,5,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
20,2007-05-29,"North Streeter Drive, Chicago, IL 60611, USA",CULEX RESTUANS,53,N STREETER DR,T129,"5300 N STREETER DR, Chicago, IL",41.891126,-87.611560,5,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
21,2007-05-29,"6500 North Oak Park Avenue, Chicago, IL 60631,...",CULEX PIPIENS/RESTUANS,65,N OAK PARK AVE,T143,"6500 N OAK PARK AVE, Chicago, IL",41.999129,-87.795585,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
22,2007-05-29,"7500 North Oakley Avenue, Chicago, IL 60645, USA",CULEX PIPIENS/RESTUANS,75,N OAKLEY AVE,T148,"7500 N OAKLEY AVE, Chicago, IL",42.017430,-87.687769,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
23,2007-05-29,"1500 North Long Avenue, Chicago, IL 60651, USA",CULEX RESTUANS,15,N LONG AVE,T153,"1500 N LONG AVE, Chicago, IL",41.907645,-87.760886,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
24,2007-05-29,"8900 South Carpenter Street, Chicago, IL 60620...",CULEX RESTUANS,89,S CARPENTER ST,T159,"8900 S CARPENTER ST, Chicago, IL",41.732984,-87.649642,8,...,BR HZ,0,M,0.0,0.00,29.39,30.11,5.8,18,6.5
25,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,RA BR,0,M,0.0,0.42,29.10,29.79,5.2,5,7.6
26,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,RA BR,0,M,0.0,0.42,29.10,29.79,5.2,5,7.6
27,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,RA BR,0,M,0.0,0.42,29.10,29.79,5.2,5,7.6
28,2007-06-05,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,...,RA BR,0,M,0.0,0.42,29.10,29.79,5.2,5,7.6
29,2007-06-05,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,...,RA BR,0,M,0.0,0.42,29.10,29.79,5.2,5,7.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10476,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,5,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10477,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX RESTUANS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,5,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10478,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX PIPIENS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,5,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10479,2013-09-26,"5800 North Pulaski Road, Chicago, IL 60646, USA",CULEX PIPIENS,58,N PULASKI RD,T027,"5800 N PULASKI RD, Chicago, IL",41.984809,-87.728492,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10480,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX PIPIENS/RESTUANS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10481,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX RESTUANS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10482,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX PIPIENS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10483,2013-09-26,"9100 West Higgins Road, Rosemont, IL 60018, USA",CULEX RESTUANS,91,W HIGGINS RD,T009,"9100 W HIGGINS RD, Chicago, IL",41.992478,-87.862995,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10484,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS/RESTUANS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10485,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS/RESTUANS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10486,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10487,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10488,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10489,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10490,2013-09-26,"4800 West Montana Street, Chicago, IL 60639, USA",CULEX PIPIENS/RESTUANS,48,W MONTANA ST,T222,"4800 W MONTANA ST, Chicago, IL",41.925198,-87.746381,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10491,2013-09-26,"5100 North Mont Clare Avenue, Chicago, IL 6065...",CULEX PIPIENS/RESTUANS,51,N MONT CLARE AVE,T223,"5100 N MONT CLARE AVE, Chicago, IL",41.973845,-87.805059,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10492,2013-09-26,"5100 North Mont Clare Avenue, Chicago, IL 6065...",CULEX PIPIENS,51,N MONT CLARE AVE,T223,"5100 N MONT CLARE AVE, Chicago, IL",41.973845,-87.805059,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10493,2013-09-26,"8200 South Kostner Avenue, Chicago, IL 60652, USA",CULEX PIPIENS/RESTUANS,82,S KOSTNER AVE,T225,"8200 S KOSTNER AVE, Chicago, IL",41.743402,-87.731435,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10494,2013-09-26,"East 91st Place, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,65,E 91ST PL,T227,"6500 E 91ST PL, Chicago, IL",41.728495,-87.600963,5,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10495,2013-09-26,"East 91st Place, Chicago, IL, USA",CULEX PIPIENS,65,E 91ST PL,T227,"6500 E 91ST PL, Chicago, IL",41.728495,-87.600963,5,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10496,2013-09-26,"1700 West Addison Street, Chicago, IL 60613, USA",CULEX PIPIENS/RESTUANS,17,W ADDISON ST,T224,"1700 W ADDISON ST, Chicago, IL",41.947227,-87.671457,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10497,2013-09-26,"West Garfield Boulevard, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,90,W GARFIELD BLVD,T226,"9000 W GARFIELD BLVD, Chicago, IL",41.793818,-87.654234,5,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10498,2013-09-26,"1300 North Laramie Avenue, Chicago, IL 60651, USA",CULEX PIPIENS/RESTUANS,13,N LARAMIE AVE,T230,"1300 N LARAMIE AVE, Chicago, IL",41.904194,-87.756155,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10499,2013-09-26,"1300 North Laramie Avenue, Chicago, IL 60651, USA",CULEX PIPIENS,13,N LARAMIE AVE,T230,"1300 N LARAMIE AVE, Chicago, IL",41.904194,-87.756155,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10500,2013-09-26,"3900 North Springfield Avenue, Chicago, IL 606...",CULEX PIPIENS/RESTUANS,39,N SPRINGFIELD AVE,T228,"3900 N SPRINGFIELD AVE, Chicago, IL",41.951866,-87.725057,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10501,2013-09-26,"5100 West 72nd Street, Chicago, IL 60638, USA",CULEX PIPIENS/RESTUANS,51,W 72ND ST,T035,"5100 W 72ND ST, Chicago, IL",41.763733,-87.742302,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10502,2013-09-26,"5800 North Ridge Avenue, Chicago, IL 60660, USA",CULEX PIPIENS/RESTUANS,58,N RIDGE AVE,T231,"5800 N RIDGE AVE, Chicago, IL",41.987280,-87.666066,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10503,2013-09-26,"1700 North Ashland Avenue, Chicago, IL 60622, USA",CULEX PIPIENS/RESTUANS,17,N ASHLAND AVE,T232,"1700 N ASHLAND AVE, Chicago, IL",41.912563,-87.668055,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10504,2013-09-26,"7100 North Harlem Avenue, Chicago, IL 60631, USA",CULEX PIPIENS/RESTUANS,71,N HARLEM AVE,T233,"7100 N HARLEM AVE, Chicago, IL",42.009876,-87.807277,9,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2
10505,2013-09-26,"4200 West 65th Street, Chicago, IL 60621, USA",CULEX PIPIENS/RESTUANS,42,W 65TH ST,T235,"4200 W 65TH ST, Chicago, IL",41.776428,-87.627096,8,...,BR,0,M,0.0,0.00,29.34,30.04,3.8,8,4.2

In [6]:
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

# Create X
### Make dummy variables of categorical

In [8]:
#mosquito species dummies
mos_dum = pd.get_dummies(df['Species'], drop_first= True)

mos_dum

,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS
0,0,1,0,0,0,0
1,0,0,1,0,0,0
2,0,0,1,0,0,0
3,0,1,0,0,0,0
4,0,0,1,0,0,0
5,0,0,1,0,0,0
6,0,0,1,0,0,0
7,0,1,0,0,0,0
8,0,0,1,0,0,0
9,0,0,1,0,0,0
10,0,1,0,0,0,0
11,0,1,0,0,0,0
12,0,0,1,0,0,0
13,0,1,0,0,0,0
14,0,0,1,0,0,0
15,0,0,1,0,0,0
16,0,0,1,0,0,0
17,0,0,1,0,0,0
18,1,0,0,0,0,0
19,0,1,0,0,0,0
20,0,0,1,0,0,0
21,0,1,0,0,0,0
22,0,1,0,0,0,0
23,0,0,1,0,0,0
24,0,0,1,0,0,0
25,0,1,0,0,0,0
26,0,0,1,0,0,0
27,1,0,0,0,0,0
28,0,1,0,0,0,0
29,0,0,1,0,0,0
...,...,...,...,...,...,...
10476,0,1,0,0,0,0
10477,0,0,1,0,0,0
10478,1,0,0,0,0,0
10479,1,0,0,0,0,0
10480,0,1,0,0,0,0
10481,0,0,1,0,0,0
10482,1,0,0,0,0,0
10483,0,0,1,0,0,0
10484,0,1,0,0,0,0
10485,0,1,0,0,0,0
10486,1,0,0,0,0,0
10487,1,0,0,0,0,0
10488,1,0,0,0,0,0
10489,1,0,0,0,0,0
10490,0,1,0,0,0,0
10491,0,1,0,0,0,0
10492,1,0,0,0,0,0
10493,0,1,0,0,0,0
10494,0,1,0,0,0,0
10495,1,0,0,0,0,0
10496,0,1,0,0,0,0
10497,0,1,0,0,0,0
10498,0,1,0,0,0,0
10499,1,0,0,0,0,0
10500,0,1,0,0,0,0
10501,0,1,0,0,0,0
10502,0,1,0,0,0,0
10503,0,1,0,0,0,0
10504,0,1,0,0,0,0
10505,0,1,0,0,0,0

In [9]:
X_o = df.loc[:, ['SeaLevel', 'Tavg', 'AvgSpeed', 'DewPoint', 'NumMosquitos']]

In [10]:
X = df.loc[:, ['SeaLevel', 'Tavg', 'AvgSpeed', 'DewPoint', 'NumMosquitos']]

In [11]:
X = X.join(mos_dum)

In [12]:
y = df['WnvPresent']

In [13]:
X

,SeaLevel,Tavg,AvgSpeed,DewPoint,NumMosquitos,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS
0,30.11,74,6.5,58,1,0,1,0,0,0,0
1,30.11,74,6.5,58,1,0,0,1,0,0,0
2,30.11,74,6.5,58,1,0,0,1,0,0,0
3,30.11,74,6.5,58,1,0,1,0,0,0,0
4,30.11,74,6.5,58,4,0,0,1,0,0,0
5,30.11,74,6.5,58,2,0,0,1,0,0,0
6,30.11,74,6.5,58,1,0,0,1,0,0,0
7,30.11,74,6.5,58,1,0,1,0,0,0,0
8,30.11,74,6.5,58,2,0,0,1,0,0,0
9,30.11,74,6.5,58,1,0,0,1,0,0,0
10,30.11,74,6.5,58,1,0,1,0,0,0,0
11,30.11,74,6.5,58,2,0,1,0,0,0,0
12,30.11,74,6.5,58,3,0,0,1,0,0,0
13,30.11,74,6.5,58,1,0,1,0,0,0,0
14,30.11,74,6.5,58,1,0,0,1,0,0,0
15,30.11,74,6.5,58,1,0,0,1,0,0,0
16,30.11,74,6.5,58,3,0,0,1,0,0,0
17,30.11,74,6.5,58,5,0,0,1,0,0,0
18,30.11,74,6.5,58,1,1,0,0,0,0,0
19,30.11,74,6.5,58,1,0,1,0,0,0,0
20,30.11,74,6.5,58,2,0,0,1,0,0,0
21,30.11,74,6.5,58,1,0,1,0,0,0,0
22,30.11,74,6.5,58,1,0,1,0,0,0,0
23,30.11,74,6.5,58,1,0,0,1,0,0,0
24,30.11,74,6.5,58,1,0,0,1,0,0,0
25,29.79,56,7.6,48,3,0,1,0,0,0,0
26,29.79,56,7.6,48,5,0,0,1,0,0,0
27,29.79,56,7.6,48,1,1,0,0,0,0,0
28,29.79,56,7.6,48,1,0,1,0,0,0,0
29,29.79,56,7.6,48,2,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
10476,30.04,63,4.2,52,2,0,1,0,0,0,0
10477,30.04,63,4.2,52,1,0,0,1,0,0,0
10478,30.04,63,4.2,52,1,1,0,0,0,0,0
10479,30.04,63,4.2,52,5,1,0,0,0,0,0
10480,30.04,63,4.2,52,5,0,1,0,0,0,0
10481,30.04,63,4.2,52,5,0,0,1,0,0,0
10482,30.04,63,4.2,52,4,1,0,0,0,0,0
10483,30.04,63,4.2,52,1,0,0,1,0,0,0
10484,30.04,63,4.2,52,39,0,1,0,0,0,0
10485,30.04,63,4.2,52,4,0,1,0,0,0,0
10486,30.04,63,4.2,52,16,1,0,0,0,0,0
10487,30.04,63,4.2,52,9,1,0,0,0,0,0
10488,30.04,63,4.2,52,11,1,0,0,0,0,0
10489,30.04,63,4.2,52,1,1,0,0,0,0,0
10490,30.04,63,4.2,52,1,0,1,0,0,0,0
10491,30.04,63,4.2,52,11,0,1,0,0,0,0
10492,30.04,63,4.2,52,1,1,0,0,0,0,0
10493,30.04,63,4.2,52,3,0,1,0,0,0,0
10494,30.04,63,4.2,52,7,0,1,0,0,0,0
10495,30.04,63,4.2,52,1,1,0,0,0,0,0
10496,30.04,63,4.2,52,3,0,1,0,0,0,0
10497,30.04,63,4.2,52,8,0,1,0,0,0,0
10498,30.04,63,4.2,52,13,0,1,0,0,0,0
10499,30.04,63,4.2,52,5,1,0,0,0,0,0
10500,30.04,63,4.2,52,3,0,1,0,0,0,0
10501,30.04,63,4.2,52,6,0,1,0,0,0,0
10502,30.04,63,4.2,52,5,0,1,0,0,0,0
10503,30.04,63,4.2,52,1,0,1,0,0,0,0
10504,30.04,63,4.2,52,5,0,1,0,0,0,0
10505,30.04,63,4.2,52,1,0,1,0,0,0,0

In [14]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10506 entries, 0 to 10505
Data columns (total 11 columns):
SeaLevel                  10506 non-null object
Tavg                      10506 non-null object
AvgSpeed                  10506 non-null object
DewPoint                  10506 non-null int64
NumMosquitos              10506 non-null int64
CULEX PIPIENS             10506 non-null uint8
CULEX PIPIENS/RESTUANS    10506 non-null uint8
CULEX RESTUANS            10506 non-null uint8
CULEX SALINARIUS          10506 non-null uint8
CULEX TARSALIS            10506 non-null uint8
CULEX TERRITANS           10506 non-null uint8
dtypes: int64(2), object(3), uint8(6)
memory usage: 874.0+ KB

In [15]:
X['SeaLevel'] = pd.to_numeric(X.SeaLevel)
X['Tavg'] = pd.to_numeric(X.Tavg)
X['AvgSpeed'] = pd.to_numeric(X.AvgSpeed)

In [16]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10506 entries, 0 to 10505
Data columns (total 11 columns):
SeaLevel                  10506 non-null float64
Tavg                      10506 non-null int64
AvgSpeed                  10506 non-null float64
DewPoint                  10506 non-null int64
NumMosquitos              10506 non-null int64
CULEX PIPIENS             10506 non-null uint8
CULEX PIPIENS/RESTUANS    10506 non-null uint8
CULEX RESTUANS            10506 non-null uint8
CULEX SALINARIUS          10506 non-null uint8
CULEX TARSALIS            10506 non-null uint8
CULEX TERRITANS           10506 non-null uint8
dtypes: float64(2), int64(3), uint8(6)
memory usage: 874.0 KB

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [18]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9512752188808526

In [19]:
y.value_counts(normalize = True)

0    0.947554
1    0.052446
Name: WnvPresent, dtype: float64

In [21]:
X_o['SeaLevel'] = pd.to_numeric(X.SeaLevel)
X_o['Tavg'] = pd.to_numeric(X.Tavg)
X_o['AvgSpeed'] = pd.to_numeric(X.AvgSpeed)


from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures()
X_o_poly = poly.fit_transform(X_o)

In [22]:
df2 = pd.DataFrame(X_o_poly)
df3 = df2.join(mos_dum)
df3

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS
0,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,1,0,0,0,0
1,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,0,1,0,0,0
2,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,0,1,0,0,0
3,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,1,0,0,0,0
4,1.0,30.11,74.0,6.5,58.0,4.0,906.6121,2228.14,195.715,1746.38,...,26.0,3364.0,232.0,16.0,0,0,1,0,0,0
5,1.0,30.11,74.0,6.5,58.0,2.0,906.6121,2228.14,195.715,1746.38,...,13.0,3364.0,116.0,4.0,0,0,1,0,0,0
6,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,0,1,0,0,0
7,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,1,0,0,0,0
8,1.0,30.11,74.0,6.5,58.0,2.0,906.6121,2228.14,195.715,1746.38,...,13.0,3364.0,116.0,4.0,0,0,1,0,0,0
9,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,0,1,0,0,0
10,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,1,0,0,0,0
11,1.0,30.11,74.0,6.5,58.0,2.0,906.6121,2228.14,195.715,1746.38,...,13.0,3364.0,116.0,4.0,0,1,0,0,0,0
12,1.0,30.11,74.0,6.5,58.0,3.0,906.6121,2228.14,195.715,1746.38,...,19.5,3364.0,174.0,9.0,0,0,1,0,0,0
13,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,1,0,0,0,0
14,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,0,1,0,0,0
15,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,0,1,0,0,0
16,1.0,30.11,74.0,6.5,58.0,3.0,906.6121,2228.14,195.715,1746.38,...,19.5,3364.0,174.0,9.0,0,0,1,0,0,0
17,1.0,30.11,74.0,6.5,58.0,5.0,906.6121,2228.14,195.715,1746.38,...,32.5,3364.0,290.0,25.0,0,0,1,0,0,0
18,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,1,0,0,0,0,0
19,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,1,0,0,0,0
20,1.0,30.11,74.0,6.5,58.0,2.0,906.6121,2228.14,195.715,1746.38,...,13.0,3364.0,116.0,4.0,0,0,1,0,0,0
21,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,1,0,0,0,0
22,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,1,0,0,0,0
23,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,0,1,0,0,0
24,1.0,30.11,74.0,6.5,58.0,1.0,906.6121,2228.14,195.715,1746.38,...,6.5,3364.0,58.0,1.0,0,0,1,0,0,0
25,1.0,29.79,56.0,7.6,48.0,3.0,887.4441,1668.24,226.404,1429.92,...,22.8,2304.0,144.0,9.0,0,1,0,0,0,0
26,1.0,29.79,56.0,7.6,48.0,5.0,887.4441,1668.24,226.404,1429.92,...,38.0,2304.0,240.0,25.0,0,0,1,0,0,0
27,1.0,29.79,56.0,7.6,48.0,1.0,887.4441,1668.24,226.404,1429.92,...,7.6,2304.0,48.0,1.0,1,0,0,0,0,0
28,1.0,29.79,56.0,7.6,48.0,1.0,887.4441,1668.24,226.404,1429.92,...,7.6,2304.0,48.0,1.0,0,1,0,0,0,0
29,1.0,29.79,56.0,7.6,48.0,2.0,887.4441,1668.24,226.404,1429.92,...,15.2,2304.0,96.0,4.0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10476,1.0,30.04,63.0,4.2,52.0,2.0,902.4016,1892.52,126.168,1562.08,...,8.4,2704.0,104.0,4.0,0,1,0,0,0,0
10477,1.0,30.04,63.0,4.2,52.0,1.0,902.4016,1892.52,126.168,1562.08,...,4.2,2704.0,52.0,1.0,0,0,1,0,0,0
10478,1.0,30.04,63.0,4.2,52.0,1.0,902.4016,1892.52,126.168,1562.08,...,4.2,2704.0,52.0,1.0,1,0,0,0,0,0
10479,1.0,30.04,63.0,4.2,52.0,5.0,902.4016,1892.52,126.168,1562.08,...,21.0,2704.0,260.0,25.0,1,0,0,0,0,0
10480,1.0,30.04,63.0,4.2,52.0,5.0,902.4016,1892.52,126.168,1562.08,...,21.0,2704.0,260.0,25.0,0,1,0,0,0,0
10481,1.0,30.04,63.0,4.2,52.0,5.0,902.4016,1892.52,126.168,1562.08,...,21.0,2704.0,260.0,25.0,0,0,1,0,0,0
10482,1.0,30.04,63.0,4.2,52.0,4.0,902.4016,1892.52,126.168,1562.08,...,16.8,2704.0,208.0,16.0,1,0,0,0,0,0
10483,1.0,30.04,63.0,4.2,52.0,1.0,902.4016,1892.52,126.168,1562.08,...,4.2,2704.0,52.0,1.0,0,0,1,0,0,0
10484,1.0,30.04,63.0,4.2,52.0,39.0,902.4016,1892.52,126.168,1562.08,...,163.8,2704.0,2028.0,1521.0,0,1,0,0,0,0
10485,1.0,30.04,63.0,4.2,52.0,4.0,902.4016,1892.52,126.168,1562.08,...,16.8,2704.0,208.0,16.0,0,1,0,0,0,0
10486,1.0,30.04,63.0,4.2,52.0,16.0,902.4016,1892.52,126.168,1562.08,...,67.2,2704.0,832.0,256.0,1,0,0,0,0,0
10487,1.0,30.04,63.0,4.2,52.0,9.0,902.4016,1892.52,126.168,1562.08,...,37.8,2704.0,468.0,81.0,1,0,0,0,0,0
10488,1.0,30.04,63.0,4.2,52.0,11.0,902.4016,1892.52,126.168,1562.08,...,46.2,2704.0,572.0,121.0,1,0,0,0,0,0
10489,1.0,30.04,63.0,4.2,52.0,1.0,902.4016,1892.52,126.168,1562.08,...,4.2,2704.0,52.0,1.0,1,0,0,0,0,0
10490,1.0,30.04,63.0,4.2,52.0,1.0,902.4016,1892.52,126.168,1562.08,...,4.2,2704.0,52.0,1.0,0,1,0,0,0,0
10491,1.0,30.04,63.0,4.2,52.0,11.0,902.4016,1892.52,126.168,1562.08,...,46.2,2704.0,572.0,121.0,0,1,0,0,0,0
10492,1.0,30.04,63.0,4.2,52.0,1.0,902.4016,1892.52,126.168,1562.08,...,4.2,2704.0,52.0,1.0,1,0,0,0,0,0
10493,1.0,30.04,63.0,4.2,52.0,3.0,902.4016,1892.52,126.168,1562.08,...,12.6,2704.0,156.0,9.0,0,1,0,0,0,0
10494,1.0,30.04,63.0,4.2,52.0,7.0,902.4016,1892.52,126.168,1562.08,...,29.4,2704.0,364.0,49.0,0,1,0,0,0,0
10495,1.0,30.04,63.0,4.2,52.0,1.0,902.4016,1892.52,126.168,1562.08,...,4.2,2704.0,52.0,1.0,1,0,0,0,0,0
10496,1.0,30.04,63.0,4.2,52.0,3.0,902.4016,1892.52,126.168,1562.08,...,12.6,2704.0,156.0,9.0,0,1,0,0,0,0
10497,1.0,30.04,63.0,4.2,52.0,8.0,902.4016,1892.52,126.168,1562.08,...,33.6,2704.0,416.0,64.0,0,1,0,0,0,0
10498,1.0,30.04,63.0,4.2,52.0,13.0,902.4016,1892.52,126.168,1562.08,...,54.6,2704.0,676.0,169.0,0,1,0,0,0,0
10499,1.0,30.04,63.0,4.2,52.0,5.0,902.4016,1892.52,126.168,1562.08,...,21.0,2704.0,260.0,25.0,1,0,0,0,0,0
10500,1.0,30.04,63.0,4.2,52.0,3.0,902.4016,1892.52,126.168,1562.08,...,12.6,2704.0,156.0,9.0,0,1,0,0,0,0
10501,1.0,30.04,63.0,4.2,52.0,6.0,902.4016,1892.52,126.168,1562.08,...,25.2,2704.0,312.0,36.0,0,1,0,0,0,0
10502,1.0,30.04,63.0,4.2,52.0,5.0,902.4016,1892.52,126.168,1562.08,...,21.0,2704.0,260.0,25.0,0,1,0,0,0,0
10503,1.0,30.04,63.0,4.2,52.0,1.0,902.4016,1892.52,126.168,1562.08,...,4.2,2704.0,52.0,1.0,0,1,0,0,0,0
10504,1.0,30.04,63.0,4.2,52.0,5.0,902.4016,1892.52,126.168,1562.08,...,21.0,2704.0,260.0,25.0,0,1,0,0,0,0
10505,1.0,30.04,63.0,4.2,52.0,1.0,902.4016,1892.52,126.168,1562.08,...,4.2,2704.0,52.0,1.0,0,1,0,0,0,0

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df3, y)

In [33]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
scale_train = ss.fit_transform(X_train)
scale_test = ss.transform(X_test)

In [34]:
lr2 = LogisticRegression()
lr2.fit(scale_train, y_train)
lr2.score(scale_test, y_test)

0.9421393224210126